---
apiVersion: database.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: mase-postgres
spec:
  classSelector:
    matchLabels:
      example: "true"
      engine: postgresql
  writeConnectionSecretToRef:
    name: postgresql-conn
  engineVersion: "9.6"